[package]
name = "pachimanga-native"
version = "0.4.0"
description = "Native shell for Pachimanga"
authors = ["Frogidev"]
edition = "2021"

[lib]
name = "pachimanga_native"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.1", features = [] }

[dependencies]
tauri = { version = "2.11.1", features = [] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "gzip", "brotli", "deflate"] }
