import type {LibraryEntry,Manga,ReaderSettings,ReadingHistoryEntry,ReadingProgress} from '@/types/models';
import {idbDelete,idbGet,idbGetAll,idbPut} from '@/lib/storage/idb';
export const DEFAULT_READER_SETTINGS:ReaderSettings={autoScrollMultiplier:1,baseSpeedPxPerSecond:120,fitMode:'width',theme:'dark'};
async function signedIn(){try{const {createClient}=await import('@/lib/supabase/client');const sb=createClient();const {data:{user}}=await sb.auth.getUser();return user?{sb,user}:null}catch{return null}}
function sourceIdFromMangaId(mangaId:string){if(mangaId.startsWith('wc-'))return 'weebcentral';if(mangaId.startsWith('ck-'))return 'comick';if(mangaId.startsWith('md-'))return 'mangadex';return 'mock'}
export async function getLibraryEntries(){return idbGetAll<LibraryEntry>('library')}
export async function addLibraryEntry(mangaId:string,sourceId='mock',manga?:Manga){const entry:LibraryEntry={mangaId,sourceId,addedAt:new Date().toISOString(),manga};await idbPut('library',entry as unknown as Record<string,unknown>);window.dispatchEvent(new CustomEvent('pachimanga:library-change'));void (async()=>{const auth=await signedIn();if(!auth)return;await auth.sb.from('library_entries').upsert({user_id:auth.user.id,manga_id:mangaId,source_id:sourceId,title:manga?.title||mangaId,cover_url:manga?.coverUrl||null,updated_at:new Date().toISOString()},{onConflict:'user_id,source_id,manga_id'})})();return entry}
export async function removeLibraryEntry(mangaId:string){await idbDelete('library',mangaId);window.dispatchEvent(new CustomEvent('pachimanga:library-change'));void (async()=>{const auth=await signedIn();if(auth)await auth.sb.from('library_entries').delete().eq('user_id',auth.user.id).eq('manga_id',mangaId)})()}
export async function seedLibrary(mangaIds:string[]){const existing=await getLibraryEntries();if(existing.length>0)return existing;return Promise.all(mangaIds.map(id=>addLibraryEntry(id)))}
export async function getProgress(chapterId:string){const local=await idbGet<ReadingProgress>('progress',chapterId);if(local)return local;const auth=await signedIn();if(!auth)return undefined;const {data}=await auth.sb.from('reading_progress').select('manga_id,chapter_id,page_index,scroll_progress,updated_at').eq('user_id',auth.user.id).eq('chapter_id',chapterId).maybeSingle();if(!data)return undefined;const p:ReadingProgress={mangaId:data.manga_id,chapterId:data.chapter_id,pageIndex:data.page_index,scrollPosition:0,percentage:Number(data.scroll_progress)*100,updatedAt:data.updated_at};await idbPut('progress',p as unknown as Record<string,unknown>);return p}
export async function saveProgress(progress:ReadingProgress){await idbPut('progress',progress as unknown as Record<string,unknown>);const history:ReadingHistoryEntry={mangaId:progress.mangaId,chapterId:progress.chapterId,percentage:progress.percentage,readAt:progress.updatedAt};await idbPut('history',history as unknown as Record<string,unknown>);window.dispatchEvent(new CustomEvent('pachimanga:history-change'));void (async()=>{const auth=await signedIn();if(!auth)return;const sourceId=sourceIdFromMangaId(progress.mangaId);await Promise.all([auth.sb.from('reading_progress').upsert({user_id:auth.user.id,source_id:sourceId,manga_id:progress.mangaId,chapter_id:progress.chapterId,page_index:progress.pageIndex,scroll_progress:progress.percentage/100,completed:progress.percentage>=99,updated_at:progress.updatedAt},{onConflict:'user_id,source_id,chapter_id'})])})()}
export async function getHistory(){const history=await idbGetAll<ReadingHistoryEntry>('history');return history.sort((a,b)=>b.readAt.localeCompare(a.readAt))}
export function getReaderSettings():ReaderSettings{if(typeof window==='undefined')return DEFAULT_READER_SETTINGS;try{const raw=localStorage.getItem('pachimanga:reader-settings')||localStorage.getItem('frogilab:reader-settings');return raw?{...DEFAULT_READER_SETTINGS,...JSON.parse(raw)}:DEFAULT_READER_SETTINGS}catch{return DEFAULT_READER_SETTINGS}}
export function saveReaderSettings(settings:ReaderSettings){localStorage.setItem('pachimanga:reader-settings',JSON.stringify(settings));void (async()=>{const auth=await signedIn();if(auth)await auth.sb.from('user_settings').upsert({user_id:auth.user.id,settings:{reader:settings},updated_at:new Date().toISOString()},{onConflict:'user_id'})})()}
