-- Reference only. Production schema is defined exclusively by timestamped migrations
-- in ../../supabase/migrations and must not be recreated from this file.
--
-- This file intentionally contains no executable DDL so it cannot drift into a
-- second schema source of truth. Inspect the canonical migration chain instead.
