'use client';
import {useState} from 'react';import {parseBackup} from '@/lib/imports';import {extractTitlesFromImage} from '@/lib/imports/ocr';import type {ImportManga} from '@/lib/imports/types';import type {Manga} from '@/types/models';import {createClient} from '@/lib/supabase/client';
type Candidate=ImportManga&{match?:Manga;selected?:boolean};
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
export function ImportPanel(){const [items,setItems]=useState<Candidate[]>([]);const [status,setStatus]=useState('');const [warnings,setWarnings]=useState<string[]>([]);const [progress,setProgress]=useState(0);const [matching,setMatching]=useState(false);
async function backup(file:File){setStatus('Reading backup…');try{const out=await parseBackup(file);setItems(out.manga.map(x=>({...x,selected:true})));setWarnings(out.warnings);setStatus(`Found ${out.manga.length} titles. Progress is preserved where the backup exposes it.`)}catch(e){setStatus(e instanceof Error?e.message:'Import failed')}}
async function image(file:File){setStatus('Scanning image on this device…');setProgress(0);try{const titles=await extractTitlesFromImage(file,setProgress);setItems(titles.map(title=>({title,favorite:true,selected:true})));setStatus(`OCR found ${titles.length} candidate titles. Review and match them before importing.`)}catch(e){setStatus(e instanceof Error?e.message:'OCR failed')}}
async function findMatch(index:number){const item=items[index];const r=await fetch(`/api/source/weebcentral/search?q=${encodeURIComponent(item.title)}`);const j=await r.json();const match=(j.items||[])[0] as Manga|undefined;setItems(v=>v.map((x,i)=>i===index?{...x,match}:x));return Boolean(match)}
async function matchBatch(){setMatching(true);setStatus('Matching titles against WeebCentral…');let found=0;try{for(let i=0;i<Math.min(items.length,20);i++){if(await findMatch(i))found++;await sleep(250)}setStatus(`Matched ${found} of the first ${Math.min(items.length,20)} titles. You can match additional rows individually.`)}finally{setMatching(false)}}
async function save(){try{const sb=createClient();const {data:{user}}=await sb.auth.getUser();if(!user)throw new Error('Sign in before importing to cloud sync.');const chosen=items.filter(x=>x.selected!==false);const rows=chosen.map((m,i)=>({user_id:user.id,manga_id:m.match?.id||`import-${i}-${m.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,60)}`,source_id:m.match?.sourceId||'import',title:m.match?.title||m.title,cover_url:m.match?.coverUrl||null,updated_at:new Date().toISOString()}));for(const row of rows){const {error}=await sb.from('library_entries').upsert(row,{onConflict:'user_id,source_id,manga_id'});if(error)throw error}setStatus(`Imported ${rows.length} titles into your private account.`)}catch(e){setStatus(e instanceof Error?e.message:'Could not save import')}}
function patch(i:number,p:Partial<Candidate>){setItems(v=>v.map((x,n)=>n===i?{...x,...p}:x))}
return <div className="grid gap-5"><div className="grid gap-4 md:grid-cols-2"><label className="rounded-3xl border border-white/8 bg-white/[.025] p-5"><h2 className="font-semibold">Scan screenshot / image</h2><p className="mt-2 text-sm leading-6 text-zinc-500">OCR runs in your browser. The image itself is not uploaded to Pachimanga.</p><input className="mt-5 block w-full text-sm text-zinc-400" type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&void image(e.target.files[0])}/>{progress>0&&progress<1&&<div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-pink-400" style={{width:`${progress*100}%`}}/></div>}</label><label className="rounded-3xl border border-white/8 bg-white/[.025] p-5"><h2 className="font-semibold">Import app backup</h2><p className="mt-2 text-sm leading-6 text-zinc-500">Tachiyomi/Mihon <code>.tachibk</code>, Tachimanga <code>.tmb</code>, or JSON.</p><input className="mt-5 block w-full text-sm text-zinc-400" type="file" accept=".tachibk,.proto.gz,.gz,.tmb,.json" onChange={e=>e.target.files?.[0]&&void backup(e.target.files[0])}/></label></div>{status&&<p className="text-sm text-zinc-400">{status}</p>}{warnings.map(w=><p className="text-sm text-amber-300" key={w}>{w}</p>)}{items.length>0&&<section className="rounded-3xl border border-white/8 bg-white/[.025] p-4 sm:p-5"><div className="flex flex-wrap items-center gap-3"><strong>{items.length} candidates</strong><span className="flex-1"/><button disabled={matching} className="rounded-xl bg-white/8 px-4 py-2 text-sm disabled:opacity-50" onClick={()=>void matchBatch()}>{matching?'Matching…':'Match first 20'}</button><button className="rounded-xl bg-pink-400 px-4 py-2 text-sm font-semibold text-[#28101c]" onClick={()=>void save()}>Import selected</button></div><div className="mt-4 grid gap-2">{items.slice(0,150).map((m,i)=><div className="grid gap-3 rounded-2xl border border-white/7 p-3 sm:grid-cols-[auto_1fr_auto] sm:items-center" key={`${m.title}-${i}`}><input type="checkbox" checked={m.selected!==false} onChange={e=>patch(i,{selected:e.target.checked})}/><div className="min-w-0"><input className="w-full bg-transparent font-medium outline-none" value={m.title} onChange={e=>patch(i,{title:e.target.value,match:undefined})}/><div className="mt-1 text-xs text-zinc-500">{m.match?`Matched: ${m.match.title} · WeebCentral`:m.lastChapterRead?`Imported progress: chapter ${m.lastChapterRead}${m.lastPageRead?` · page ${m.lastPageRead}`:''}`:'Not matched yet'}</div></div><button onClick={()=>void findMatch(i)} className="rounded-xl bg-white/7 px-3 py-2 text-xs">Find match</button></div>)}</div></section>}</div>}
