import type { Chapter,Manga,Page } from '@/types/models';
const BASE='https://weebcentral.com';
const decode=(s:string)=>s.replace(/&amp;/g,'&').replace(/&#39;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const visibleText=(html:string)=>decode(html.replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' '));
const attr=(tag:string,name:string)=>{const m=tag.match(new RegExp(`${name}=["']([^"']+)["']`,'i'));return m?.[1]};
export function parseSearchHtml(html:string):Manga[]{const out:Manga[]=[];const seen=new Set<string>();for(const m of html.matchAll(/<a\b[^>]*href=["'](?:https?:\/\/weebcentral\.com)?\/series\/([0-9A-Z]{20,32})(?:\/[^"']*)?["'][^>]*>([\s\S]*?)<\/a>/gi)){const id=m[1];if(seen.has(id))continue;const inner=m[2];const title=decode(inner.replace(/<img[\s\S]*?>/gi,''));const img=inner.match(/<img\b[^>]*>/i)?.[0];const cover=img&&(attr(img,'src')||attr(img,'data-src'));if(!title||title.length>180)continue;seen.add(id);out.push({id:`wc-${id}`,sourceId:'weebcentral',title,alternativeTitles:[],description:'',coverUrl:cover?new URL(cover,BASE).toString():'/icons/icon-512.png',author:'',artist:'',status:'unknown',genres:[],sourceUrl:`${BASE}/series/${id}`})}return out.slice(0,60)}
function textAfter(html:string,label:string){const re=new RegExp(`${label}[^:<]{0,30}:?\\s*(?:<[^>]+>\\s*)*([^<\\n]{1,240})`,'i');return decode(html.match(re)?.[1]||'')}
export function parseMangaHtml(html:string,id:string):Manga{const h1=decode(html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||'Untitled');const imgs=[...html.matchAll(/<img\b[^>]*>/gi)].map(x=>x[0]);const coverTag=imgs.find(t=>/cover/i.test(attr(t,'alt')||''))||imgs.find(t=>/series/i.test(attr(t,'src')||''));const cover=coverTag&&(attr(coverTag,'src')||attr(coverTag,'data-src'));
const descMatch=html.match(/(?:Description[\s\S]{0,600}?)(?:<p\b[^>]*>|<div\b[^>]*>)([\s\S]*?)(?:<\/p>|<\/div>)/i);const description=decode(descMatch?.[1]||'');const author=textAfter(html,'Author\\(s\\)')||textAfter(html,'Author');const statusRaw=(visibleText(html).match(/\bStatus\s*:\s*(Complete(?:d)?|Ongoing|Hiatus|Cancel(?:led|ed))\b/i)?.[1]||textAfter(html,'Status')).toLowerCase();const status=statusRaw.includes('complete')?'complete':statusRaw.includes('ongoing')?'ongoing':statusRaw.includes('hiatus')?'hiatus':statusRaw.includes('cancel')?'cancelled':'unknown';const tagsRaw=textAfter(html,'Tag\\(s\\)')||textAfter(html,'Tags');const genres=tagsRaw?tagsRaw.split(',').map(x=>x.trim()).filter(Boolean):[];return {id:`wc-${id}`,sourceId:'weebcentral',title:h1,alternativeTitles:[],description,coverUrl:cover?new URL(cover,BASE).toString():'/icons/icon-512.png',author,artist:'',status,genres,sourceUrl:`${BASE}/series/${id}`}}
export function parseChaptersHtml(html:string,mangaId:string):Chapter[]{const rows:Chapter[]=[];const seen=new Set<string>();for(const m of html.matchAll(/<a\b[^>]*href=["'](?:https?:\/\/weebcentral\.com)?\/chapters\/([0-9A-Z]{20,32})["'][^>]*>([\s\S]*?)<\/a>/gi)){const id=m[1];if(seen.has(id))continue;const title=decode(m[2]).replace(/\s*last\s*read\s.*$/i,'').trim()||'Chapter';const num=Number(title.match(/(?:chapter|ch\.?)[\s#-]*([0-9]+(?:\.[0-9]+)?)/i)?.[1]||title.match(/([0-9]+(?:\.[0-9]+)?)\s*$/)?.[1]||0);seen.add(id);rows.push({id:`wc-${id}`,mangaId:`wc-${mangaId}`,sourceId:'weebcentral',title,chapterNumber:Number.isFinite(num)?num:0,sourceUrl:`${BASE}/chapters/${id}`})}return rows.sort((a,b)=>b.chapterNumber-a.chapterNumber)}
export function parsePagesHtml(html:string):Page[]{const urls:string[]=[];for(const tag of html.matchAll(/<img\b[^>]*>/gi)){const value=attr(tag[0],'src')||attr(tag[0],'data-src')||attr(tag[0],'data-lazy-src');if(!value)continue;const u=new URL(value,BASE);if(!/\.(?:jpe?g|png|webp|avif)(?:\?|$)/i.test(u.href))continue;if(/logo|icon|avatar|cover/i.test(u.href))continue;urls.push(u.href)}for(const m of html.matchAll(/https?:\\?\/\\?\/[^"'<>\s]+?\.(?:jpe?g|png|webp|avif)(?:\?[^"'<>\s]*)?/gi)){urls.push(m[0].replaceAll('\\/','/'))}return [...new Set(urls)].map((imageUrl,index)=>({index,imageUrl,width:1200,height:1800}))}
export function parseChapterSeriesId(html:string){return html.match(/href=["'](?:https?:\/\/weebcentral\.com)?\/series\/([0-9A-Z]{20,32})/i)?.[1]}
export function parseChapterTitle(html:string){return decode(html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)?.[1]||'Chapter')}
