import type {MangaSource} from '@/sources/core/manga-source';
import {SourceUnavailableError} from '@/sources/core/manga-source';
import {parseChapterSeriesId,parseChapterTitle,parseChaptersHtml,parseMangaHtml,parsePagesHtml,parseSearchHtml} from './parser';
const BASE='https://weebcentral.com';
const ID=/^[0-9A-Z]{20,32}$/;
function rawId(value:string){const id=value.replace(/^wc-/,'');if(!ID.test(id))throw new Error('Invalid WeebCentral identifier.');return id}
async function wcFetch(path:string,revalidate=300){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const res=await fetch(`${BASE}${path}`,{headers:{'User-Agent':'Pachimanga/0.4 (+https://frogilab.dev)','Accept':'text/html,application/xhtml+xml','HX-Request':'true','Referer':`${BASE}/`},signal:controller.signal,next:{revalidate}});if(res.status===429)throw new SourceUnavailableError('WeebCentral','rate limited; try again later');if(!res.ok)throw new SourceUnavailableError('WeebCentral',`HTTP ${res.status}`);return await res.text()}catch(e){if(e instanceof SourceUnavailableError)throw e;if(e instanceof Error&&e.name==='AbortError')throw new SourceUnavailableError('WeebCentral','request timed out');throw new SourceUnavailableError('WeebCentral','network request failed')}finally{clearTimeout(timer)}}
export class WeebCentralSource implements MangaSource{readonly id='weebcentral';readonly name='WeebCentral';async search(query:string){const q=query.trim().replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').slice(0,100);if(!q)return [];const html=await wcFetch(`/search?text=${encodeURIComponent(q)}`,60);return parseSearchHtml(html)}async getManga(id:string){const rid=rawId(id);return parseMangaHtml(await wcFetch(`/series/${rid}`,300),rid)}async getChapters(mangaId:string){const rid=rawId(mangaId);return parseChaptersHtml(await wcFetch(`/series/${rid}/full-chapter-list`,120),rid)}async getChapterPages(chapterId:string){const rid=rawId(chapterId);const pages=parsePagesHtml(await wcFetch(`/chapters/${rid}`,3600));if(!pages.length)throw new SourceUnavailableError('WeebCentral','no readable page images were found');return pages}}
export const weebCentralSource=new WeebCentralSource();

export async function getWeebCentralChapterContext(chapterId:string){const rid=rawId(chapterId);const html=await wcFetch(`/chapters/${rid}`,3600);const mangaRaw=parseChapterSeriesId(html);if(!mangaRaw)throw new SourceUnavailableError('WeebCentral','chapter series could not be resolved');const [manga,chapters]=await Promise.all([weebCentralSource.getManga(mangaRaw),weebCentralSource.getChapters(mangaRaw)]);const chapter=chapters.find(c=>c.id===`wc-${rid}`)||{id:`wc-${rid}`,mangaId:manga.id,sourceId:'weebcentral',title:parseChapterTitle(html),chapterNumber:0,sourceUrl:`${BASE}/chapters/${rid}`};const pages=parsePagesHtml(html);if(!pages.length)throw new SourceUnavailableError('WeebCentral','no readable page images were found');return {manga,chapter,chapters,pages}}
