create unique index if not exists library_entries_user_source_manga_idx on public.library_entries(user_id,source_id,manga_id);
create unique index if not exists reading_progress_user_source_chapter_idx on public.reading_progress(user_id,source_id,chapter_id);
create table if not exists public.reading_history(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 source_id text not null,
 manga_id text not null,
 chapter_id text not null,
 percentage double precision not null default 0 check (percentage between 0 and 100),
 read_at timestamptz not null default now(),
 unique(user_id,source_id,manga_id)
);
alter table public.reading_history enable row level security;
grant select,insert,update,delete on public.reading_history to authenticated;
create policy "history self select" on public.reading_history for select to authenticated using ((select auth.uid())=user_id);
create policy "history self insert" on public.reading_history for insert to authenticated with check ((select auth.uid())=user_id);
create policy "history self update" on public.reading_history for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "history self delete" on public.reading_history for delete to authenticated using ((select auth.uid())=user_id);
