create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.library_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  source_id text not null,
  manga_id text not null,
  title text not null,
  cover_url text,
  added_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, source_id, manga_id)
);

create table if not exists public.reading_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  source_id text not null,
  manga_id text not null,
  chapter_id text not null,
  page_index integer not null default 0 check (page_index >= 0),
  scroll_progress double precision not null default 0 check (scroll_progress >= 0 and scroll_progress <= 1),
  completed boolean not null default false,
  updated_at timestamptz not null default now(),
  unique (user_id, source_id, manga_id, chapter_id)
);

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.library_entries enable row level security;
alter table public.reading_progress enable row level security;
alter table public.user_settings enable row level security;

create policy "profiles_select_own" on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy "profiles_insert_own" on public.profiles for insert to authenticated with check ((select auth.uid()) = id);
create policy "profiles_update_own" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy "library_select_own" on public.library_entries for select to authenticated using ((select auth.uid()) = user_id);
create policy "library_insert_own" on public.library_entries for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "library_update_own" on public.library_entries for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "library_delete_own" on public.library_entries for delete to authenticated using ((select auth.uid()) = user_id);

create policy "progress_select_own" on public.reading_progress for select to authenticated using ((select auth.uid()) = user_id);
create policy "progress_insert_own" on public.reading_progress for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "progress_update_own" on public.reading_progress for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "progress_delete_own" on public.reading_progress for delete to authenticated using ((select auth.uid()) = user_id);

create policy "settings_select_own" on public.user_settings for select to authenticated using ((select auth.uid()) = user_id);
create policy "settings_insert_own" on public.user_settings for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "settings_update_own" on public.user_settings for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

revoke all on public.profiles, public.library_entries, public.reading_progress, public.user_settings from anon;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.library_entries to authenticated;
grant select, insert, update, delete on public.reading_progress to authenticated;
grant select, insert, update on public.user_settings to authenticated;
grant usage, select on all sequences in schema public to authenticated;
